### ISSUE TITLE
Incorporate feedback from last year's course

### ISSUE THREAD

**Issue by fabianschoeni** [C2SM/climate-model-workshop#4]
Key points from last year's feedback to consider for the next course:

- Longer coffee breaks, as the conversations during breaks were the most fruitful
- Link to CH2018 (and outlook to CH2025) and how the climate models treated in the workshop feed into these climate scenarios
- The exercises were appreciated by most participants

Complete feedback: 
[Summary_Feedback_ClimateModelWorkshop_061223.pdf](https://github.com/C2SM/climate-model-workshop/files/13961966/Summary_Feedback_ClimateModelWorkshop_061223.pdf)

**Comment by ruthlorenz** [comment]
We changed the agenda slightly to have a longer coffee break, added info about CH2018 and CH2025.
